# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MeterReader.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import enums_pb2 as enums__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11MeterReader.proto\x1a\x0b\x65nums.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n\rReadingPacket\x12!\n\x08readings\x18\x01 \x03(\x0b\x32\x0f.ReadingMessage\x12\r\n\x05notes\x18\x02 \x01(\t\x12\"\n\nsuccessful\x18\x03 \x01(\x0e\x32\x0e.ReadingStatus\"}\n\x0eReadingMessage\x12\x12\n\ncustomerId\x18\x01 \x01(\x05\x12\x14\n\x0creadingValue\x18\x02 \x01(\x05\x12/\n\x0breadingTime\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampJ\x04\x08\x03\x10\x04R\nsuccessful\"A\n\rStatusMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1f\n\x07success\x18\x02 \x01(\x0e\x32\x0e.ReadingStatus2C\n\x13MeterReadingService\x12,\n\nAddReading\x12\x0e.ReadingPacket\x1a\x0e.StatusMessageB\x1a\xaa\x02\x17MeterReaderWeb.Servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MeterReader_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\027MeterReaderWeb.Services'
  _globals['_READINGPACKET']._serialized_start=67
  _globals['_READINGPACKET']._serialized_end=168
  _globals['_READINGMESSAGE']._serialized_start=170
  _globals['_READINGMESSAGE']._serialized_end=295
  _globals['_STATUSMESSAGE']._serialized_start=297
  _globals['_STATUSMESSAGE']._serialized_end=362
  _globals['_METERREADINGSERVICE']._serialized_start=364
  _globals['_METERREADINGSERVICE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
